### ISSUE TITLE
can you support 1.0.0-rc4-004597

### ISSUE THREAD

**Issue by AbhimanyuAryan** [friism/dotnet-buildpack#3]
I am using 1.0.0-rc4-004597 on my macbook pro which uses .cproj instead to .json. Can you support .csproj projects? 

```

remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to stark-scrubland-80801.
remote:
To https://git.heroku.com/stark-scrubland-80801.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/stark-scrubland-80801.git'
```

**Comment by friism** [comment]
I added a branch that uses csproj: 

    heroku buildpacks:set https://github.com/friism/dotnet-buildpack#move-to-msbuild

https://github.com/friism/dotnet-buildpack/compare/master...friism:move-to-msbuild
